config/routes.rb
DoINeedVisa::Application.routes.draw do

  root 'index#index'

  post '/' => 'index#search'

  scope '/admin' do
    get '/', to: redirect('/admin/visa_sources')

    resources :visa_sources

    get '/page_hash', to: 'page_hash#calculate'
  end

end

app/models/search_form.rb
class SearchForm
  attr_accessor :result, :searched
  attr_reader :citizen, :country

  def initialize(citizen, country)
    @citizen = citizen.upcase if citizen
    @country = country.upcase if country
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User
end

app/models/visa.rb
class Visa < ActiveRecord::Base
  validates :citizen, presence: true
  validates :citizen, length: { is: 2 }

  belongs_to :visa_source
end

app/models/visa_source.rb
class VisaSource < ActiveRecord::Base
  has_many :visas, dependent: :destroy

  validates :name, :country, :url, :description, presence: true

  validates :name, :url, length: { maximum: 255 }
  validates :country, length: { is: 2 }

  def visa_codes
    visas.collect { |visa| visa.citizen }
  end

  def visa_codes=(codes)
    # delete all that are no longer in the codes collection
    visas.each { |visa|
      visas.destroy(visa) unless codes.include? visa.citizen
    }

    codes.each { |code|
      if visas.none? { |visa| visa.citizen == code }
        visas << Visa.new(citizen: code, visa_source: self)
      end
    }
    save!
  end

  def ==(comparison_object)
    attributes == comparison_object.attributes
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller

  layout 'admin'

  protect_from_forgery with: :exception
end

app/controllers/index_controller.rb
class IndexController < ApplicationController

  layout 'public'

  def index
    @search_form = SearchForm.new(request_country(request.remote_ip), nil)
  end

  def search
    @search_form = SearchForm.new(params[:search_form][:citizen], params[:search_form][:country])
    @search_form.searched = true
    @search_form.result = find_visa_source(@search_form)

    render :index
  end

  private

  def request_country(ip)
    geo = GeoIP.new('vendor/assets/geoip/GeoIP.dat')
    country = geo.country(ip).country_code2
    country.upcase! unless country.nil?
    country
  end

  def find_visa_source(form)
    VisaSource.joins(:visas).where(country: form.country, visas: {citizen: form.citizen}).first
  end
end

app/controllers/page_hash_controller.rb
require_relative '../../lib/tasks/page_hash'

class PageHashController < ApplicationController
  force_ssl if Rails.env.production?

  before_filter :require_login

  def calculate
    page_hash = PageHash.calculate(params[:url], params[:selector])
    render json: {page_hash: page_hash}
  end
end

app/controllers/visa_sources_controller.rb
class VisaSourcesController < ApplicationController

  force_ssl if Rails.env.production?

  before_filter :require_login

  def index

  end

  def new
    @visa_source = VisaSource.new
  end

  def edit
    @visa_source = VisaSource.find(params[:id])
  end

  def create
    @visa_source = VisaSource.create(source_params)
    if @visa_source.invalid?
      flash[:errors] = @visa_source.errors.messages
      render :new
    else
      update_visa_codes(@visa_source, params)
      redirect_to action: :index
    end
  end

  def update
    @visa_source = VisaSource.find(params['id'])
    @visa_source.update(source_params)
    if @visa_source.invalid?
      flash[:errors] = @visa_source.errors.messages
      render :edit
    else
      update_visa_codes(@visa_source, params)
      redirect_to action: :index
    end
  end

  def destroy
    to_delete = VisaSource.find(params['id'])
    to_delete.destroy unless to_delete.visas.size > 0
    redirect_to action: :index
  end

  private

  def source_params
    params.require(:visa_source).permit(:name, :country, :url, :selector, :page_hash, :visa_required, :on_arrival, :description)
  end

  def update_visa_codes(visa_source, params)
    submitted_country_codes = params['visa_source']['visa_codes']
    visa_source.visa_codes = submitted_country_codes.select { |code| !code.blank? } unless submitted_country_codes.nil?
  end
end

app/views/index/index.html.erb
<h1>Do I need visa?</h1>
<p class="lead">
    <%= form_tag '/', {method: 'post', class: 'form-inline'} do %>
        I am from <%= country_select(:search_form, :citizen, {iso_codes: true},  {class: 'form-control'}) %>.
        Do I need visa for <%= country_select(:search_form, :country, {iso_codes: true}, {class: 'form-control'}) %>
        <%=	submit_tag '?', {class: 'btn btn-default'} %>
    <% end %>
</p>

<% if @search_form.searched %>
<p class="lead">
    <% if @search_form.citizen == @search_form.country %>
        No, you really do not need a visa for your own country!
    <% elsif @search_form.result.nil? %>
        Unfortunately we do not know.

        However your request has been logged and we'll try to update our records as soon as possible.
    <% elsif @search_form.result.visa_required? %>
        Unfortunately you do need a visa!
        <% if @search_form.result.on_arrival? %>
            But you can get it on arrival.
        <% end %>
    <% else %>
        Luckily you do not need visa!
    <% end %>

    <% unless @search_form.result.nil? || @search_form.result.description.blank? %>
        <% content_tag(:p, @search_form.result.description) %>
    <% end %>
</p>
<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Visa Source Management</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'admin', media: 'all' %>
    <%= javascript_include_tag 'admin' %>
    <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
    <%= yield %>
</div>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Do I Need Visa?</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag "application", :media => "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
    <%= yield %>
</div>

</body>
</html>

app/views/layouts/public.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Do I Need Visa?</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'public', media: 'all' %>
    <%= javascript_include_tag 'public' %>
    <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
    <%= yield %>
</div>

</body>
</html>

app/views/visa_sources/_form.erb
<div class="form-group <%= raw('has-error has-feedback') unless src.errors[:name].empty? %>">
    <%=	form.label :name, 'Name', {class: 'col-md-3 control-label'} %>

    <div class="col-md-8 controls">
        <%= form.text_field :name, {class: 'form-control'} %>
    </div>
</div>
<div class="form-group <%= raw('has-error has-feedback') unless src.errors[:country].empty? %>">
    <%=	form.label :country, 'Country', {class: 'col-md-3 control-label'} %>

    <div class="col-md-8 controls">
        <%= form.country_select :country, nil, {iso_codes: true}, {class: 'chosen-select'} %>
    </div>
</div>
<div class="form-group <%= raw('has-error has-feedback') unless src.errors[:url].empty? %>">
    <%=	form.label :url, 'URL', {class: 'col-md-3 control-label'} %>

    <div class="col-md-8 controls">
        <%= form.url_field :url, {class: 'form-control'} %>
    </div>
</div>
<div class="form-group <%= raw('has-error has-feedback') unless src.errors[:selector].empty? %>">
    <%=	form.label :selector, 'CSS Selector', {class: 'col-md-3 control-label'} %>

    <div class="col-md-8 controls">
        <%= form.text_field :selector, {class: 'form-control'} %>
    </div>
</div>
<div class="form-group <%= raw('has-error has-feedback') unless src.errors[:page_hash].empty? %>">
    <%=	form.label :page_hash, 'Page Hash', {class: 'col-md-3 control-label'} %>

    <div class="col-md-8 controls">
        <%= form.text_field :page_hash, {class: 'form-control'} %>
    </div>
</div>
<div class="form-group <%= raw('has-error has-feedback') unless src.errors[:page_hash].empty? %>">
    <a id="current-hash" class="col-md-3 control-label" href="#">Current Page Hash</a>
    <div class="col-md-8 controls"></div>
</div>
<div class="form-group <%= raw('has-error has-feedback') unless src.errors[:visa_required].empty? %>">
    <div class="col-md-offset-3 col-md-8">
        <label class="checkbox">
            <%= form.check_box :visa_required %>
            Visa required
        </label>
    </div>
</div>
<div class="form-group <%= raw('has-error has-feedback') unless src.errors[:on_arrival].empty? %>">
    <div class="col-md-offset-3 col-md-8">
        <label class="checkbox">
            <%= form.check_box :on_arrival %>
            Visa on arrival
        </label>
    </div>
</div>
<div class="form-group">
    <label class="col-md-3 control-label">Applies to citizens of</label>

    <div class="col-md-8 controls">
        <%= form.select :visa_codes, Country.all.sort_by { |elem| elem[0] }, {}, {multiple: true, class: 'chosen-select'} %>
    </div>
</div>
<div class="form-group <%= raw('has-error has-feedback') unless src.errors[:description].empty? %>">
    <label class="col-md-3 control-label">Description</label>

    <div class="col-md-8">
        <%= form.text_area :description, {class: 'form-control', rows: '10'} %>
    </div>
</div>
<div class="form-group mt">
    <div class="col-md-offset-3 col-md-8">
        <button type="submit" class="btn btn-primary"><%= btn_label %></button>
        <%= link_to 'Back to Sources', {controller: 'visa_sources', action: 'index'}, {class: 'btn btn-default', role: 'button'} %>
    </div>
</div>

app/views/visa_sources/edit.html.erb
<h1>Update Visa Source</h1>

<div class="narrow">
    <%=	form_for(@visa_source, html: {role: 'form', class: 'form-horizontal', autofill: 'off'}) do |form| %>
        <%= render partial: 'form', locals: {form: form, src: @visa_source, btn_label: 'Update Source'} %>
    <% end %>
</div>

app/views/visa_sources/index.html.erb
<% require 'countries' %>

<h1>Visa Sources</h1>

<%= link_to 'Add New', { controller: 'visa_sources', action: 'new' }, class: 'btn btn-default' %>

<% if VisaSource.all.size > 0 %>
    <div class="panel panel-default mt">
        <table class="table table-striped">
            <thead>
            <tr>
                <th>Name</th>
                <th>Country</th>
                <th>Updated</th>
                <th>Countries</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            <% VisaSource.all.each { |source| %>
                <tr>
                    <td><%= link_to source.name, edit_visa_source_path(source) %></td>
                    <td><%= Country.find_country_by_alpha2(source.country) %></td>
                    <td><%= source.updated? %></td>
                    <td><%= source.visas.size %></td>
                    <td><%= link_to 'Delete', visa_source_path(source), method: :delete %></td>
                </tr>
            <% } %>
            </tbody>
        </table>
    </div>
<% end %>

app/views/visa_sources/new.html.erb
<h1>Create New Visa Source</h1>

<div class="narrow">
    <%=	form_for(@visa_source, html: {role: 'form', class: 'form-horizontal', autofill: 'off'}) do |form| %>
        <%= render partial: 'form', locals: {form: form, src: @visa_source, btn_label: 'Create Source'} %>
    <% end %>
</div>